export class Student {
    studentID: string;
    userID: string;
    authLevel: string;
    inquiryDate: string;
    username: string;
    password: string;
    fullName: string;
    firstName: string;
    lastName: string;
    birthdate: string;
    email: string;
    phone: string;
    okayToText: boolean;
    allowDetailedMessage: boolean;
    longDistance: boolean;
    alternateNumber: string;
    okayToTextAlternate: boolean;
    allowDetailedMessageAlternate: boolean;
    longDistanceAlternate: boolean;
    comments: string;
    enrolled: boolean;
    absent: boolean;
    studentStartDate: Date;
    studentEndDate: Date;
    attendanceValue: any;
    editConsentRequest: boolean;
    editConsentPermission: boolean;
}
